server:
  port: 8088

auth0:
  audience: https://tiendasplus/api

spring:
  application:
    name: tiendasplus

  datasource:
    url: jdbc:postgresql://postgresql-14282-0.cloudclusters.net:14282/tiendaplus
    username: admin 
    password: admin123

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-h5l34moo.us.auth0.com/
  jpa:
    open-in-view: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl